name: CI


on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    outputs:
      zip_path: ${{ steps.Build.outputs.zip_path }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
    
      - name: Clone
        uses: actions/checkout@v4

      # Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Build python script into a stand-alone
      - name: Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app.py
          onefile: true

      - name: Build
        id: build
        run: |
          ls build/
          zip -r app-linux.zip build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: translate-linux.zip


  macOS-latest:
    runs-on: macos-latest
    outputs:
      zip_path: ${{ steps.Build.outputs.zip_path }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
    
      - name: Clone
        uses: actions/checkout@v4

      # Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Build python script into a stand-alone
      - name: Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app.py
          onefile: true

      - name: Build
        id: build
        run: |
          ls build/
          zip -r app-drawin.zip build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: app-drawin.zip

  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [Release]
        arch: [Win32, x64]
        sdl2: [ON]
        include:
          - arch: Win32
            s2arc: x86
          - arch: x64
            s2arc: x64
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
    
      - name: Clone
        uses: actions/checkout@v4

      # Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Build python script into a stand-alone
      - name: Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app.py
          onefile: true

      - name: Build
        id: build
        run: |
          ls build/
          Compress-Archive -Path ./build -DestinationPath app-${{ matrix.arch }}.zip

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: app-${{ matrix.arch }}.zip

  
  release:
    needs: [ubuntu-latest, macOS-latest, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifact/app-Win32.zip
            artifact/app-drawin.zip
            artifact/app-linux.zip
            artifact/app-x64.zip